# Generated by Django 4.2.4 on 2023-08-22 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecartapp', '0004_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
    ]
